spring:
  cloud:
    gateway:
      # 配置路由规则
      routes:
      #  - id: lion-auth
      #    uri: lb://lion-auth
      #    predicates:
      #      - Path=/auth/**
      #    filters:
      #      - StripPrefix=1

      #  - id: lion-upms
      #    uri: lb://lion-upms
      #    predicates:
      #      - Path=/upms/**
      #    filters:
      #      - StripPrefix=1

      #  - id: lion-id
      #    uri: lb://lion-id
      #    predicates:
      #      - Path=/id/**
      #    filters:
      #      - StripPrefix=1

      #  - id: lion-bigdata
      #    uri: lb://lion-bigdata
      #    predicates:
      #      - Path=/bigdata/**
      #    filters:
      #      - StripPrefix=1

      #  - id: lion-blockchain
      #    uri: lb://lion-blockchain
      #    predicates:
      #      - Path=/blockchain/**
      #    filters:
      #      - StripPrefix=1

      #  - id: lion-demo-provider
      #    uri: lb://lion-demo-provider
      #    predicates:
      #      - Path=/demo/provider/**
      #    filters:
      #      - StripPrefix=2

      #  - id: lion-demo-consumer
      #    uri: lb://lion-demo-consumer
      #    predicates:
      #      - Path=/demo/consumer/**
      #    filters:
      #      - StripPrefix=2

    sentinel:
      transport:
        dashboard: localhost:8080
  rabbitmq:
    host: ${RABBIT_MQ_HOST:182.92.217.85}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admin}
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:8884
    sender:
      type: rabbit
  redis:
    host: ${REDIS_HOST:182.92.217.85}
    port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always