spring:
  sleuth:
    enabled: false
    sampler:
      probability: 1.0

zipkin:
  collector:
    rabbitmq:
      addresses: ${RABBIT_MQ_ADDRESS:182.92.217.85:5672}
      username: ${RABBIT_MQ_USERNAME:admin}
      password: ${RABBIT_MQ_PASSWORD:admin}
      queue: ${RABBIT_MQ_QUEUE:zipkin}
  #开发环境使用mysql存储
  storage:
    type: mysql
    mysql:
      jdbc-url: jdbc:mysql://182.92.217.85:3306/flower_zipkin_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
      host: 182.92.217.85
      port: 3306
      username: root
      password: Passw0rd_
      db: flower_zipkin_dev
      max-active: 10
      use-ssl: false
  #生产环境使用elasticsearch存储
  #storage:
    #type: elasticsearch
    #elasticsearch:
      #hosts: 182.92.217.85:9200
      #max-requests: 64
      #timeout: 10000
      #index: zipkin
      #index-shards: 5
      #index-replicas: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    web:
      server:
        auto-time-requests: false